# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '新闻',
                'verbose_name': '新闻',
            },
        ),
    ]
